### ISSUE TITLE
refs with IPLD: yml or json or toml file

### ISSUE THREAD

**Issue by jbenet** [ipfs/gateway-dmca-denylist#6]
once IPLD lands, we can keep the whole refs dag in one (or a collection of) config files. and we can use `json, yml, toml` as source:

a valid refs.ipfs.io source file:

``` yml

---
# this is the src file for refs.ipfs.io

lists:
  denylists:
    dmca: {mlink: <ref-for-dmca>}

# solarnet is the ipfs cluster running bootstrap + gateway (ipfs.io) nodes.
solarnet:
  motd: {mlink: /ipfs/<ref-for-motd>}
  bootstrap: {mlink: <ref-for-bootstrap-list>}
  gateway: {mlink: <ref-for-gateways-list>}
```
